---

################################
# BASICS
################################

radarr_prometheus_is_enabled: '{{ (radarr_prometheus_env_timezone is defined) and
                                  (radarr_prometheus_env_timezone is not none) and
                                  (radarr_prometheus_env_timezone | trim | length > 0) and
                                  (radarr_prometheus_env_puid is defined) and
                                  (radarr_prometheus_env_puid is not none) and
                                  (radarr_prometheus_env_puid | trim | length > 0) and
                                  (radarr_prometheus_env_pgid is defined) and
                                  (radarr_prometheus_env_pgid is not none) and
                                  (radarr_prometheus_env_pgid | trim | length > 0) }}'

################################
# COMMANDS
################################

radarr_prometheus_commands:
  - '--config.file=/etc/prometheus/prometheus.yml'
  - '--storage.tsdb.path=/data'
  - '--storage.tsdb.retention.time={{ radarr_prometheus_metrics_retention_time }}'
  - '--storage.tsdb.retention.size={{ radarr_prometheus_metrics_retention_size }}'

################################
# NETWORK
################################

radarr_prometheus_network_is_enabled: '{{ (radarr_prometheus_network_driver is defined) and
                                          (radarr_prometheus_network_driver is not none) and
                                          (radarr_prometheus_network_driver | trim | length > 0) and
                                          (radarr_prometheus_network_subnet is defined) and
                                          (radarr_prometheus_network_subnet is not none) and
                                          (radarr_prometheus_network_subnet | trim | length > 0) }}'

radarr_prometheus_network_default_bind:
  - name: '{{ radarr_network_backend }}'
radarr_prometheus_network_traefik_bind:
  - name: '{{ radarr_prometheus_traefik_network }}'
radarr_prometheus_network_bind:
  - name: '{{ radarr_prometheus_network }}'

radarr_prometheus_docker_networks: '{{ radarr_prometheus_network_default_bind
                                       + (radarr_prometheus_network_traefik_bind
                                          if radarr_prometheus_traefik_is_enabled
                                          else [])
                                       + (radarr_prometheus_network_bind
                                          if radarr_prometheus_is_enabled
                                          else []) }}'

################################
# BINDS
################################

radarr_prometheus_volumes_binds: '{{ radarr_prometheus_binds_config_mapping
                                     + radarr_prometheus_binds_data_mapping }}'

################################
# TRAEFIK
################################

radarr_prometheus_traefik_labels_default:
  traefik.enable: 'true'
  traefik.docker.network: '{{ radarr_prometheus_traefik_network }}'

radarr_prometheus_traefik_labels_router:
  traefik.http.routers.prometheus-rtr.entrypoints: 'http'
  traefik.http.routers.prometheus-rtr.rule: 'Host(`{{ radarr_prometheus_traefik_subdomain }}.{{ radarr_prometheus_traefik_domain }}`)'
  traefik.http.routers.prometheus-rtr.middlewares: 'globalHeaders@file,robotHeaders@file,authelia@docker'
  traefik.http.routers.prometheus-rtr.priority: '20'
  traefik.http.routers.prometheus-rtr.service: 'prometheus-rtr-svc'
  traefik.http.services.prometheus-rtr-svc.loadbalancer.server.port: '{{ radarr_prometheus_traefik_port }}'

radarr_prometheus_traefik_labels_router_secure:
  traefik.http.routers.prometheus-rtr-secure.entrypoints: 'https'
  traefik.http.routers.prometheus-rtr-secure.rule: 'Host(`{{ radarr_prometheus_traefik_subdomain }}.{{ radarr_prometheus_traefik_domain }}`)'
  traefik.http.routers.prometheus-rtr-secure.middlewares: 'globalHeaders@file,secureHeaders@file,robotHeaders@file,authelia@docker'
  traefik.http.routers.prometheus-rtr-secure.priority: '20'
  traefik.http.routers.prometheus-rtr-secure.service: 'prometheus-rtr-secure-svc'
  traefik.http.routers.prometheus-rtr-secure.tls.certresolver: 'dns-cloudflare'
  traefik.http.routers.prometheus-rtr-secure.tls.options: 'tls-opts@file'
  traefik.http.services.prometheus-rtr-secure-svc.loadbalancer.server.port: '{{ radarr_prometheus_traefik_port }}'

radarr_prometheus_traefik_labels: '{{ radarr_prometheus_traefik_labels_default
                                      | combine(radarr_prometheus_traefik_labels_router)
                                      | combine(radarr_prometheus_traefik_labels_router_secure) }}'

radarr_prometheus_traefik_is_enabled: '{{ (radarr_prometheus_traefik_domain is defined) and
                                          (radarr_prometheus_traefik_domain is not none) and
                                          (radarr_prometheus_traefik_domain | trim | length > 0) }}'

################################
# CLOUDFLARE
################################

radarr_prometheus_cloudflare_record: '{{ radarr_prometheus_traefik_subdomain }}'
radarr_prometheus_cloudflare_zone: '{{ radarr_prometheus_traefik_domain }}'

radarr_prometheus_cloudflare_is_enabled: '{{ (radarr_prometheus_cloudflare_api_token is defined) and
                                             (radarr_prometheus_cloudflare_api_token is not none) and
                                             (radarr_prometheus_cloudflare_api_token | trim | length > 0) }}'

################################
# EXPORTER
################################

radarr_prometheus_exporter_network_default_bind:
  - name: '{{ radarr_network_backend }}'
radarr_prometheus_exporter_network_bind:
  - name: '{{ radarr_prometheus_network }}'

radarr_prometheus_exporter_networks: '{{ radarr_prometheus_exporter_network_default_bind
                                         + (radarr_prometheus_exporter_network_bind
                                            if radarr_prometheus_is_enabled
                                            else []) }}'

radarr_prometheus_exporter_is_enabled: '{{ (radarr_prometheus_exporter_env_timezone is defined) and
                                           (radarr_prometheus_exporter_env_timezone is not none) and
                                           (radarr_prometheus_exporter_env_timezone | trim | length > 0) and
                                           (radarr_prometheus_exporter_env_puid is defined) and
                                           (radarr_prometheus_exporter_env_puid is not none) and
                                           (radarr_prometheus_exporter_env_puid | trim | length > 0) and
                                           (radarr_prometheus_exporter_env_pgid is defined) and
                                           (radarr_prometheus_exporter_env_pgid is not none) and
                                           (radarr_prometheus_exporter_env_pgid | trim | length > 0) }}'

