---

################################
# DOMAIN
################################

  ## radarr
radarr_traefik_subdomain: '{{ radarr_basics_name }}'
radarr_traefik_domain: ''
radarr_traefik_port: '{{ radarr_ports_cont }}'

  ## radarr4k
radarr_4k_traefik_subdomain: '{{ radarr_4k_basics_name }}'
radarr_4k_traefik_domain: '{{ radarr_traefik_domain }}'
radarr_4k_traefik_port: '{{ radarr_4k_ports_cont }}'

  ## prometheus
radarr_prometheus_traefik_subdomain: '{{ radarr_prometheus_basics_name }}'
radarr_prometheus_traefik_domain: '{{ radarr_traefik_domain }}'
radarr_prometheus_traefik_port: '{{ radarr_prometheus_ports_cont }}'

################################
# NETWORK
################################

radarr_traefik_network: 'traefik_proxy'
radarr_traefik_network_driver: 'bridge'  ## only required if network doesn't exist
radarr_traefik_network_subnet: ''  ## only required if network doesn't exist

################################
# TLS
################################

radarr_traefik_tls_certresolver: 'dns-cloudflare'
radarr_traefik_tls_options: 'tls-opts@file'

################################
# ROUTER (HTTP)
################################

  ## radarr
radarr_traefik_http_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
radarr_traefik_http_rule: 'Host(`{{ radarr_traefik_subdomain }}.{{ radarr_traefik_domain }}`)'
radarr_traefik_http_priority: '20'

radarr_traefik_http_api_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
radarr_traefik_http_api_rule: '{{ radarr_traefik_http_rule + " && (PathPrefix(`/api`) || PathPrefix(`/feed`) || PathPrefix(`/ping`))" }}'
radarr_traefik_http_api_priority: '30'

  ## radarr4k
radarr_4k_traefik_http_middlewares: '{{ radarr_traefik_http_middlewares }}'
radarr_4k_traefik_http_rule: 'Host(`{{ radarr_4k_traefik_subdomain }}.{{ radarr_4k_traefik_domain }}`)'
radarr_4k_traefik_http_priority: '{{ radarr_traefik_http_priority }}'

radarr_4k_traefik_http_api_middlewares: '{{ radarr_traefik_http_api_middlewares }}'
radarr_4k_traefik_http_api_rule: '{{ radarr_4k_traefik_http_rule + " && (PathPrefix(`/api`) || PathPrefix(`/feed`) || PathPrefix(`/ping`))" }}'
radarr_4k_traefik_http_api_priority: '{{ radarr_traefik_http_api_priority }}'

  ## prometheus
radarr_prometheus_traefik_http_middlewares: '{{ radarr_traefik_http_middlewares }}'
radarr_prometheus_traefik_http_rule: 'Host(`{{ radarr_prometheus_traefik_subdomain }}.{{ radarr_prometheus_traefik_domain }}`)'
radarr_prometheus_traefik_http_priority: '{{ radarr_traefik_http_priority }}'

################################
# ROUTER (HTTPS)
################################

  ## radarr
radarr_traefik_https_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
radarr_traefik_https_rule: 'Host(`{{ radarr_traefik_subdomain }}.{{ radarr_traefik_domain }}`)'
radarr_traefik_https_priority: '20'

radarr_traefik_https_api_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
radarr_traefik_https_api_rule: '{{ radarr_traefik_https_rule + " && (PathPrefix(`/api`) || PathPrefix(`/feed`) || PathPrefix(`/ping`))" }}'
radarr_traefik_https_api_priority: '30'

  ## radarr4k
radarr_4k_traefik_https_middlewares: '{{ radarr_traefik_https_middlewares }}'
radarr_4k_traefik_https_rule: 'Host(`{{ radarr_4k_traefik_subdomain }}.{{ radarr_4k_traefik_domain }}`)'
radarr_4k_traefik_https_priority: '{{ radarr_traefik_https_priority }}'

radarr_4k_traefik_https_api_middlewares: '{{ radarr_traefik_https_api_middlewares }}'
radarr_4k_traefik_https_api_rule: '{{ radarr_4k_traefik_https_rule + " && (PathPrefix(`/api`) || PathPrefix(`/feed`) || PathPrefix(`/ping`))" }}'
radarr_4k_traefik_https_api_priority: '{{ radarr_traefik_https_api_priority }}'

  ## prometheus
radarr_prometheus_traefik_https_middlewares: '{{ radarr_traefik_https_middlewares }}'
radarr_prometheus_traefik_https_rule: 'Host(`{{ radarr_prometheus_traefik_subdomain }}.{{ radarr_prometheus_traefik_domain }}`)'
radarr_prometheus_traefik_https_priority: '{{ radarr_traefik_https_priority }}'

################################
# THEME-PARK
################################

  ## radarr
radarr_traefik_themepark_theme: 'hotpink'

  ## radarr4k
radarr_4k_traefik_themepark_theme: 'hotpink'