---

- name: Create recyclarr appdata directory
  ansible.builtin.file:
    path: '{{ radarr_recyclarr_paths_location }}'
    state: directory
    owner: '{{ radarr_recyclarr_env_puid }}'
    group: '{{ radarr_recyclarr_env_pgid }}'
    mode: '0755'

- name: Insert radarr's recyclarr secrets settings
  ansible.builtin.blockinfile:
    path: '{{ radarr_recyclarr_paths_location }}/secrets.yml'
    marker: "## {mark} ANSIBLE RADARR MANAGED BLOCK ##"
    owner: '{{ radarr_recyclarr_env_puid }}'
    group: '{{ radarr_recyclarr_env_pgid }}'
    mode: '0664'
    create: true
    block: |
      radarr_base_url: http://{{ radarr_basics_name }}:{{ radarr_ports_cont }}
      radarr_api_key: {{ radarr_api_key }}
  notify:
    - restart recyclarr

- name: Insert radarr's recyclarr config settings
  ansible.builtin.blockinfile:  ## these are settings I use. Yours may differ. See: https://recyclarr.dev/wiki/
    path: '{{ radarr_recyclarr_paths_location }}/recyclarr.yml'
    marker: "## {mark} ANSIBLE RADARR MANAGED BLOCK ##"
    owner: '{{ radarr_recyclarr_env_puid }}'
    group: '{{ radarr_recyclarr_env_pgid }}'
    mode: '0664'
    create: true
    block: |
      radarr:
        radarr:
          media_naming:
            folder: plex
            movie:
              rename: true
              standard: default
          quality_definition:
            type: movie
          quality_profiles:
            - name: "Remux + WEB 1080p"
              reset_unmatched_scores:
                enabled: true
              upgrade:
                allowed: true
                until_quality: Remux-1080p
                until_score: 10000
              min_format_score: 0
              quality_sort: top
              qualities:
                - name: Remux-1080p
                - name: Bluray-1080p
                  enabled: false
                - name: "WEB 1080p"
                  qualities:
                    - WEBRip-1080p
                    - WEBDL-1080p
          delete_old_custom_formats: true
          replace_existing_custom_formats: true
          custom_formats:
            - trash_ids:
                  # Audio Advanced #1
                - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
                - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
                - 185f1dd7264c4562b9022d963ac37424 # DD+
                - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
                - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
                - 2f22d89048b01681dde8afe203bf2e95 # DTS X
                - 1c1a4c5e823891c75bc50380a6866f73 # DTS
                - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
                - 3cafb66171b47f226146a0770576870f # TrueHD
                  # Audio Advanced #2
                - 240770601cc226190c367ef59aba7463 # AAC
                - c2998bd0d90ed5621d8df281e839436e # DD
                - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
                - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
                - 6ba9033150e7896bdc9ec4b44f2b230f # MP3
                - a061e2e700f81932daf888599f8a8273 # Opus
                - e7c2fcae07cbada050a0af3357491d7b # PCM
                  # HDR Formats
                - e23edd2482476e595fb990b12e7c609c # DV HDR10
                - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
                - a3e19f8f627608af0211acd02bf89735 # DV SDR
                - 58d6a88f13e2db7f5059c41047876f00 # DV
                - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
                - e61e28db95d22bedcadf030b8f156d96 # HDR
                - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
                - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
                - 9364dd386c9b4a1100dde8264690add7 # HLG
                - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
                  # HQ Release Groups
                - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
                - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
                - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
                - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
                - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
                - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
                - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
                - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
                - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
                - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
                - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
                - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
                  # Misc
                - 0d91270a7255a1e388fa85e959f359d8 # FreeLeech
                - ff86c4326018682f817830ced463332b # MPEG2
                - 4b900e171accbfb172729b63323ea8ca # Multi
                - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
                - ae43b294509409a6a13919dedd4764c4 # Repack2
                - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
                - 2899d84dc9372de3408e6d8cc18e9666 # x264
                  # Movie Versions
                - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
                - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
                - 0f12c086e289cf966fa5948eac571f44 # Hybrid
                - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
                - eecf3a857724171f968a66cb5719e152 # IMAX
                - 570bc9ebecd92723d2d21500f4be314c # Remaster
                - 957d0f44b592285f26449575e8b1167e # Special Edition
                - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
                - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
                - 09d9dd29a0fc958f9796e65c2a8864b4 # Open Matte
                - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
                  # Unwanted
                - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
                - ed38b889b31be83fda192888e2286d83 # BR-DISK
                - 90a6f9a284dff5103f6346090e6280c8 # LQ
                - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
                - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
                - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
                  # Asian Streaming Services
                - 917d1f2c845b2b466036b0cc2d7c72a3 # FOD
                - 834b2c0ba0a8596029b4479a29e1a032 # HTSR
                - 26df36e3d2a96de2f8b7166ae37d3c33 # TVING
                - f1b0bae9bc222dab32c1b38b5a7a1088 # TVer
                - 279bda7434fd9075786de274e6c3c202 # U-NEXT
                - 1b355ff093fd1064b75ea98c616881b1 # VIU
                  # Dutch Streaming Services
                - bf7e73dd1d85b12cc527dc619761c840 # Pathe
                - 996e8ce50025e8b1e8fa95fcb28c4e5a # VDL
                  # General Streaming Services
                - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
                - 40e9380490e748672c2522eaaeb692f7 # ATVP
                - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
                - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
                - 84272245b2988854bfb76a16e60baea5 # DSNP
                - 509e5f41146e278f9eab1ddaceb34515 # HBO
                - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
                - 526d445d4c16214309f0fd2b3be18a89 # Hulu
                - 2a6039655313bf5dab1e43523b62c374 # MA
                - 6a061313d22e51e0f25b7cd4dc065233 # MAX
                - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
                - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
                - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
                - c2863d2a50c9acad1fb50e53ece60817 # STAN
                  # Misc Streaming Services
                - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
                - fbca986396c5e695ef7b2def3c755d01 # OViD
                - ab56ccdc473a1f2897c76187ea365be2 # STRP
                  # UK Streaming Services
                - 6185878161f1e2eef9cd0641a0d09eae # IP
                - c3492a26af412e385404eade438ec51c # ITVX
                - 3dce1fce9ac06d1349dfbd9186289385 # NOW
                  # Optional
                - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
                - f700d29429c023a5734505e77daeaea7 # DV (FEL)
                - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
                - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
                - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
                - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
                - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
                - c465ccc73923871b3eb1802042331306 # Line/Mic Dubbed
                - 73613461ac2cea99d52c4cd6e177ab82 # HFR
                - 9c38ebb7384dada637be8899efa68e6f # SDR
              quality_profiles:
                - name: "Remux + WEB 1080p"
  notify:
    - restart recyclarr

- name: Register recyclarr container
  community.docker.docker_container_info:
    name: '{{ radarr_recyclarr_basics_name }}'
  register: radarr_recyclarr_container_result

- name: Create recyclarr container
  when: not radarr_recyclarr_container_result.exists
  community.docker.docker_container:
    name: '{{ radarr_recyclarr_basics_name }}'
    image: '{{ radarr_recyclarr_basics_image_repo }}:{{ radarr_recyclarr_basics_image_tag }}'
    networks: '{{ radarr_network_default_bind }}'
    env:
      PUID: '{{ radarr_recyclarr_env_puid }}'
      PGID: '{{ radarr_recyclarr_env_pgid }}'
      TZ: '{{ radarr_recyclarr_env_timezone }}'
      CRON_SCHEDULE: '@daily'
      RECYCLARR_CREATE_CONFIG: 'false'
    volumes: '{{ radarr_recyclarr_bind_mount }}'
    restart_policy: '{{ radarr_recyclarr_basics_restart_policy }}'
