---

################################
# APPDATA
################################

- name: Create themepark appdata directory
  ansible.builtin.file:
    path: '{{ radarr_themepark_paths_location }}'
    state: directory
    owner: '{{ radarr_themepark_env_puid }}'
    group: '{{ radarr_themepark_env_pgid }}'
    mode: '0755'

################################
# CONTAINER
################################

- name: Create themepark container
  community.docker.docker_container:
    name: '{{ radarr_themepark_basics_name }}'
    image: '{{ radarr_themepark_basics_image_repo }}:{{ radarr_themepark_basics_image_tag }}'
    networks: '{{ radarr_network_backend }}'
    env:
      PUID: '{{ radarr_themepark_env_puid }}'
      PGID: '{{ radarr_themepark_env_pgid }}'
      TZ: '{{ radarr_themepark_env_timezone }}'
    ports:
      - '{{ radarr_themepark_ports_host }}:{{ radarr_themepark_ports_cont }}'    
    volumes: '{{ radarr_themepark_bind_mount }}'
    restart_policy: '{{ radarr_themepark_basics_restart_policy }}'