---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lookup("vars", radarr_prefix + "_4k" + "_cloudflare_api_token") }}'
    zone: '{{ lookup("vars", radarr_prefix + "_4k" + "_traefik_domain") }}'
    state: absent
    type: CNAME
    record: '{{ lookup("vars", radarr_prefix + "_4k" + "_traefik_subdomain") }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lookup("vars", radarr_prefix + "_4k" + "_cloudflare_api_token") }}'
    zone: '{{ lookup("vars", radarr_prefix + "_4k" + "_traefik_domain") }}'
    state: absent
    type: A
    record: '{{ lookup("vars", radarr_prefix + "_4k" + "_traefik_subdomain") }}'

- name: Add DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lookup("vars", radarr_prefix + "_4k" + "_cloudflare_api_token") }}'
    zone: '{{ lookup("vars", radarr_prefix + "_4k" + "_traefik_domain") }}'
    state: present
    solo: true
    proxied: '{{ lookup("vars", radarr_prefix + "_4k" + "_cloudflare_proxy") }}'
    type: '{{ lookup("vars", radarr_prefix + "_4k" + "_cloudflare_record_type") }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ lookup("vars", radarr_prefix + "_4k" + "_traefik_subdomain") }}'
  register: radarr4k_cloudflare_record_creation_status

- name: Tasks on success
  when: radarr4k_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'cloudflare_radarr4k_record_print' variable
      ansible.builtin.set_fact:
        radarr4k_cloudflare_record_print: '{{ (lookup("vars", radarr_prefix + "_4k" + "_traefik_subdomain") == lookup("vars", radarr_prefix + "_4k" + "_traefik_domain")) | ternary(lookup("vars", radarr_prefix + "_4k" + "_traefik_domain"), lookup("vars", radarr_prefix + "_4k" + "_traefik_subdomain") + "." + lookup("vars", radarr_prefix + "_4k" + "_traefik_domain")) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ radarr4k_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ lookup("vars", radarr_prefix + "_4k" + "_cloudflare_proxy") }}'
